/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sankhya.view;


import br.com.sankhya.ConnUtils.VerificadorDeBalanca;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.border.EtchedBorder;
import jssc.SerialPort;

/**
 *
 * @author Felipe
 */
public class BotaoView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    
        Boolean isOpen=Boolean.FALSE;
	Boolean isConectado=Boolean.FALSE;
	SerialPort serialPort =null;
	private Boolean isAmbienteTeste=Boolean.TRUE;
        //JComboBox jcbCOM;
        ImageIcon img = new ImageIcon("..\\Assets\\balancaIcon.png");
        
    
    public BotaoView() { 
                
        initComponents();
        
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        caixa.setEditable(false); 
        jb.setBounds(300, 300, 100, 60);
	jb2.setBounds(400, 300, 100, 60);
	sp.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); 
	caixa.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED));
	caixa.setForeground(Color.BLUE);
	caixa.setFont(new Font("Verdana", Font.BOLD, 16));
	caixa.setMargin(new Insets(10,10,10,10));
	caixa.setBounds(0, 10, 700, 600);
        this.setIconImage(img.getImage());
	//setSize(700,600);
        
        
                
        //this.jcbCOM = new JComboBox(comns.toArray());
       // jcbCOM.setVisible(true);
       this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb = new javax.swing.JToggleButton();
        sp = new javax.swing.JScrollPane();
        caixa = new javax.swing.JTextArea();
        jb2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jcbCOM = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leitor de Balança");
        setBackground(new java.awt.Color(102, 0, 102));
        setIconImage(img.getImage());

        jb.setText("Conectar");
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });

        caixa.setColumns(20);
        caixa.setRows(5);
        sp.setViewportView(caixa);

        jb2.setText("Sair");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Porta Serial:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sp)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcbCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
                        if(null != this.getJcbCOM().getSelectedItem()){
			  VerificadorDeBalanca.getInstance().verificarBalanca(isAmbienteTeste, caixa, this.getJcbCOM().getSelectedItem().toString());
                          
                          if(isConectado) {
				jb.setText("Conectar");
				isConectado=Boolean.FALSE;
                                jcbCOM.setEnabled(true);
                                jcbCOM.setEditable(true);
                                //jcbCOM.setVisible(true);
                                //this.jcbCOM.setOpaque(true);
			    }else {
				jb.setText("Desconectar");
				isConectado=Boolean.TRUE;                                
                                this.jcbCOM.setEnabled(false);
                                this.jcbCOM.setEditable(false);
                                //jcbCOM.setVisible(false);
                               // this.jcbCOM.setOpaque(false);
			    }
                        }else{
                            //("Sem Balança Conectada!!!").setVisible(true);                            
                            new JOptionPane().showMessageDialog(new JFrame(),"Sem Balança Detectada!","Aviso",JOptionPane.WARNING_MESSAGE);
                        }
                        
						
		
    }//GEN-LAST:event_jbActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jb2ActionPerformed

    public Boolean getIsAmbienteTeste() {
        return isAmbienteTeste;
    }

    protected void setIsAmbienteTeste(Boolean isAmbienteTeste) {
        this.isAmbienteTeste = isAmbienteTeste;
    }

    public JComboBox<String> getJcbCOM() {
        return jcbCOM;
    }            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BotaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea caixa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jb;
    private javax.swing.JButton jb2;
    private javax.swing.JComboBox<String> jcbCOM;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
