/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sankhya.view;


import br.com.sankhya.ConnUtils.IdentificadorDeSeriais;
import br.com.sankhya.SwingUtils.ManipuladorDeComboBox;
import br.com.sankhya.control.FormulasControle;
import br.com.sankhya.control.PainelControle;
import java.awt.Color;
import java.awt.Font;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JToggleButton;
import javax.swing.border.EtchedBorder;
import jssc.SerialPort;

/**
 *
 * @author Felipe
 */
public class BotaoView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    
        Boolean isOpen=Boolean.FALSE;	
	SerialPort serialPort =null;
	private Boolean isAmbienteTeste;
        //JComboBox jcbCOM;
        //ImageIcon img = new ImageIcon("BalancaIcone.ico");
        
        PainelControle controle;
        
    
    public BotaoView(Boolean isAmbienteTeste, PainelControle controle) { 
                
        initComponents();
        
        //this.setExtendedState(this.MAXIMIZED_BOTH);
        caixa.setEditable(false); 
        jb.setBounds(300, 300, 100, 60);
	jb2.setBounds(400, 300, 100, 60);
	sp.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS); 
	caixa.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED));
	caixa.setForeground(Color.BLUE);
	caixa.setFont(new Font("Verdana", Font.BOLD, 16));
	caixa.setMargin(new Insets(10,10,10,10));
	caixa.setBounds(0, 10, 700, 600);
        //this.setIconImage(img.getImage());
	//setSize(700,600);
        this.controle = controle;
        this.isAmbienteTeste = isAmbienteTeste;
        ManipuladorDeComboBox.getInstance().listaItens(IdentificadorDeSeriais.getInstance().listarSeriais(isAmbienteTeste), this.jcbCOM);
        
        setIcon();
        
                
        //this.jcbCOM = new JComboBox(comns.toArray());
       // jcbCOM.setVisible(true);
       this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jb = new javax.swing.JToggleButton();
        sp = new javax.swing.JScrollPane();
        caixa = new javax.swing.JTextArea();
        jb2 = new javax.swing.JButton();
        serialLabel = new javax.swing.JLabel();
        jcbCOM = new javax.swing.JComboBox<>();
        balancaLabel = new javax.swing.JLabel();
        balancaComboBox = new javax.swing.JComboBox<>();
        configButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Leitor de Balança");
        setBackground(new java.awt.Color(102, 0, 102));

        jb.setText("Conectar");
        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });

        caixa.setColumns(20);
        caixa.setRows(5);
        sp.setViewportView(caixa);

        jb2.setText("Sair");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        serialLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        serialLabel.setText("Porta Serial:");

        jcbCOM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbCOM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jcbCOMFocusLost(evt);
            }
        });
        jcbCOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbCOMMouseClicked(evt);
            }
        });
        jcbCOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCOMActionPerformed(evt);
            }
        });

        balancaLabel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        balancaLabel.setText("Balança:");

        balancaComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        balancaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Marca", "Toledo 8540", "Toledo 820" }));
        balancaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancaComboBoxActionPerformed(evt);
            }
        });

        configButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sankhya/Assets/configIcon.png"))); // NOI18N
        configButton.setToolTipText("Configurações");
        configButton.setMaximumSize(new java.awt.Dimension(49, 25));
        configButton.setMinimumSize(new java.awt.Dimension(49, 25));
        configButton.setPreferredSize(new java.awt.Dimension(49, 25));
        configButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sp)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serialLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balancaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balancaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(configButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(serialLabel)
                        .addComponent(jcbCOM, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(balancaLabel)
                        .addComponent(balancaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addComponent(sp, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
       this.controle.conectar();
    }//GEN-LAST:event_jbActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jb2ActionPerformed

    private void balancaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancaComboBoxActionPerformed
        this.controle.setBalanca(this.balancaComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_balancaComboBoxActionPerformed

    private void configButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configButtonActionPerformed
        new FormulasControle();
    }//GEN-LAST:event_configButtonActionPerformed

    private void jcbCOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCOMActionPerformed
        
    }//GEN-LAST:event_jcbCOMActionPerformed

    private void jcbCOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbCOMMouseClicked
        //this.controle.salvarPortaSerialSelecionada(this.jcbCOM.getSelectedItem().toString().substring(3));
    }//GEN-LAST:event_jcbCOMMouseClicked

    private void jcbCOMFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcbCOMFocusLost
        this.controle.salvarPortaSerialSelecionada(this.jcbCOM.getSelectedItem().toString().substring(3));
    }//GEN-LAST:event_jcbCOMFocusLost

    public Boolean getIsAmbienteTeste() {
        return isAmbienteTeste;
    }

    protected void setIsAmbienteTeste(Boolean isAmbienteTeste) {
        this.isAmbienteTeste = isAmbienteTeste;
    }

    public JComboBox<String> getJcbCOM() {
        return jcbCOM;
    }

    public JComboBox<String> getBalancaComboBox() {
        return balancaComboBox;
    }    

    public PainelControle getControle() {
        return controle;
    }

    public JToggleButton getJb() {
        return jb;
    }   

    public JTextArea getCaixa() {
        return caixa;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotaoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BotaoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> balancaComboBox;
    private javax.swing.JLabel balancaLabel;
    private javax.swing.JTextArea caixa;
    private javax.swing.JButton configButton;
    private javax.swing.JToggleButton jb;
    private javax.swing.JButton jb2;
    private javax.swing.JComboBox<String> jcbCOM;
    private javax.swing.JLabel serialLabel;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
       // this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\felip\\Documents\\NetBeansProjects\\Aplicativo_Balanca\\src\\main\\java\\br\\com\\sankhya\\view\\BalancaIcone.png"));
    }
}
